// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/17/2024, 12:18:10 PM
const configMerger = require("/Users/defiboy/Documents/zero-mono/apps/app/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.ts")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/defiboy/Documents/zero-mono/apps/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/defiboy/Documents/zero-mono/apps/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/defiboy/Documents/zero-mono/apps/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/defiboy/Documents/zero-mono/apps/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/defiboy/Documents/zero-mono/apps/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/defiboy/Documents/zero-mono/apps/app/plugins/**/*.{js,ts,mjs}","/Users/defiboy/Documents/zero-mono/apps/app/composables/**/*.{js,ts,mjs}","/Users/defiboy/Documents/zero-mono/apps/app/utils/**/*.{js,ts,mjs}","/Users/defiboy/Documents/zero-mono/apps/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/defiboy/Documents/zero-mono/apps/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/defiboy/Documents/zero-mono/apps/app/app.config.{js,ts,mjs}"] }));

module.exports = config
