blank_issues_enabled: false
contact_links:
  - name: Discord Community Support
    url: https://discord.com/channels/1231026713031606272/1292865230040465479
    about: Please ask and answer questions here.
#   - name: GitHub Security Bug Bounty
#     url: https://bounty.github.com/
#     about: Please report security vulnerabilities here.
