name: Publish Landing Page to Docker Hub

on:
  pull_request:
    branches: [ main ]

jobs:
    publish_image:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: build
              run: |
                docker build . -t lordewan/0xzero-landing:latest
              working-directory: ./apps/landing
            - name: publish
              run: |
                docker login -u lordewan -p ${{ secrets.DOCKERHUB_TOKEN }}
                docker push lordewan/0xzero-landing:latest
              working-directory: ./apps/landing