name: Publish SDK to npmjs
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: blacksmith-4vcpu-ubuntu-2204
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: useblacksmith/setup-node@v5
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm i
        working-directory: ./apps/omid/s3n/sdk
      - run: npm publish --access public
        working-directory: ./apps/omid/s3n/sdk
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

